// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE5nabv3GwikXmhLG5aUZ95lcRNyFBQls',
    appId: '1:1009741973245:web:432426d70524f9abc86094',
    messagingSenderId: '1009741973245',
    projectId: 'contact-f49bc',
    authDomain: 'contact-f49bc.firebaseapp.com',
    storageBucket: 'contact-f49bc.appspot.com',
    measurementId: 'G-2DLF51SLEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvsWX2krwYd9vr8CRM9Us-cCjf3TU1dfI',
    appId: '1:1009741973245:android:1d3a78be2590e504c86094',
    messagingSenderId: '1009741973245',
    projectId: 'contact-f49bc',
    storageBucket: 'contact-f49bc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE5nabv3GwikXmhLG5aUZ95lcRNyFBQls',
    appId: '1:1009741973245:web:09db955fd0620274c86094',
    messagingSenderId: '1009741973245',
    projectId: 'contact-f49bc',
    authDomain: 'contact-f49bc.firebaseapp.com',
    storageBucket: 'contact-f49bc.appspot.com',
    measurementId: 'G-SZ0GY4EQHY',
  );
}
